routes/web.php
<?php

Route::get('/', function () {return view('frontend.home');});
//auth & user
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/password-change', 'HomeController@changePassword')->name('password.change');
Route::post('/password-update', 'HomeController@updatePassword')->name('password.update');
Route::get('/user/logout', 'HomeController@Logout')->name('user.logout');

//admin=======
Route::get('admin/home', 'AdminController@index')->name('admin.home');
Route::get('admin', 'Admin\LoginController@admin_login')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login')->name('admin_login.store');
// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/reset/password/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/update/reset', 'Admin\ResetPasswordController@reset')->name('admin.reset.update');
Route::get('/admin/Change/Password','AdminController@ChangePassword')->name('admin.password.change');
Route::post('/admin/password/update','AdminController@Update_pass')->name('admin.password.update');
Route::get('admin/logout', 'AdminController@logout')->name('admin.logout');

// Admin routes


//For general user
Route::get('wishlist/add/{product_id}', 'WishListController@add_wishlist')->name('wishlist.add');
Route::get('cart/add/{product_id}', 'CartController@add_cart')->name('cart.add');
Route::get('product/view-cart/', 'CartController@index')->name('cart.index');
Route::get('cart/delete/{rowId}', 'CartController@destroy')->name('cart.remove');
Route::post('cart/update', 'CartController@update')->name('cart.update');
Route::get('cart/check', 'CartController@check')->name('cart.check');
Route::get('product/checkout', 'CheckOutController@checkout')->name('checkout');
Route::post('product/checkout/store', 'CheckOutController@store')->name('checkout.store');
Route::get('product/checkout/review', 'CheckOutController@review_order')->name('checkout.review');
Route::post('product/submit-order','OrderController@order')->name('checkout.order');
Route::get('product/order/cod','OrderController@cod')->name('checkout.cod');
Route::get('product/order/paypal','OrderController@paypal')->name('checkout.paypal');
//Route::get('product/checkout', 'CartController@checkout')->name('checkout');

//For admin user
// Category
Route::prefix('admin')->group(function () {
    Route::get('category/list', 'CategoryController@index')->name('category.index');
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::post('store/category', 'CategoryController@store')->name('category.store');
    Route::post('category/{id}', 'CategoryController@delete')->name('category.delete');
    Route::get('category/edit/{id}', 'CategoryController@edit')->name('category.edit');
    Route::post('category/update/{id}', 'CategoryController@update')->name('category.update');
// Brand
    Route::resource('brand', 'BrandController');
// Sub Category
    Route::resource('subcategory', 'SubCategoryController');
// Product
    Route::resource('product', 'ProductController');
    Route::get('delete-image/{id}','ProductController@deleteImage');
// Coupon
    Route::resource('coupon', 'CouponController');
/// Product Attribute
    Route::resource('attribute','ProductAttributeController');
//Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
/// Product Images Gallery
    Route::resource('/imagegallery','ImageGalleryController');
//Route::get('delete-imageGallery/{id}','ImagesController@destroy');
//    Route::resource('wishlist', 'WishListController');
});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $fillable = ['name'];



    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\Category;
use Illuminate\Http\Request;

class BrandController extends Controller
{

//    public function __construct()
//    {
//        $this->middleware('auth:admin');
//    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $brands = Brand::all();
        return view('admin.brand.index')->withBrands($brands);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.brand.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|unique:brands|max:255',
            'logo' => 'required'
        ]);

        try{
            $brand = new Brand();
            $brand->name = $request['name'];
            $logo = $request->file('logo');
            $logo_name = date('d_m_y_i');
            $ext = strtolower($logo->getClientOriginalExtension());
            $logo_full_name = $logo_name. '.' . $ext;
            $upload_path = 'media/brand/';
            $logo_url = $upload_path.$logo_full_name;
            $logo->move($upload_path, $logo_full_name);

            $brand->logo =  $logo_url;
            $brand->save();

            $notification=array(
                'message'=>"Brand created Successfully",
                'alert-type'=>'success'
            );
            return Redirect()->route('brand.index')->with($notification);
        }
        catch(Exception $e){
            Log::error($e->getMessage());
            $notification=array(
                'message'=>"Brand doesn't created",
                'alert-type'=>'error'
            );

            return Redirect()->back()->with($notification);

        }

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        $brand = Brand::findOrFail($brand)->first();

        return view('admin.brand.edit')->withBrand($brand);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {

        try{
            $brand = Brand::findOrFail($brand)->first();

            $brand->name = $request['name'];
            $logo = $request->file('logo');
            if($logo){
                unlink($request->old_logo);
                $logo_name = date('d_m_y_i');
                $ext = strtolower($logo->getClientOriginalExtension());
                $logo_full_name = $logo_name. '.' . $ext;
                $upload_path = 'media/category/';
                $logo_url = $upload_path.$logo_full_name;
                $logo->move($upload_path, $logo_full_name);

                $brand->logo =  $logo_url;
                $brand->save();

                $notification=array(
                    'message'=>"Brand Update Successfully",
                    'alert-type'=>'success'
                );
                return redirect()->route('brand.index')->with($notification);
            }
            else{
                $brand->name = $request['name'];
                $brand->save();
                $notification=array(
                    'message'=>"Brand Updated Except Logo Successfully",
                    'alert-type'=>'success'
                );
                return redirect()->route('brand.index')->with($notification);
            }
        }
        catch(Exception $e){
            $notification=array(
                'message'=>"Brand doesn't created",
                'alert-type'=>'error'
            );

            return redirect()->back()->with($notification);

        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Brand  $brand
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $brand = Brand::where('id', $id)->first();
        $logo = $brand->logo;
        unlink($logo);

        $brand->delete();
        $notification=array(
            'message'=>"Brand deleted",
            'alert-type'=>'success'
        );
        return redirect()->back()->with($notification);
    }

}

resources/views/admin/brand/create.blade.php
@extends('admin.admin_layouts')
@section('title', 'Brand Create')
@section('admin_content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card-box">
                <h4 class="header-title  text-center m-t-0 m-b-30"> Add Brand</h4>
                <form method="post" action="{{ route('brand.store') }}" enctype="multipart/form-data">
                    @csrf
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter brand name...">
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="filer_input">Brand Logo</label>
                                <input type="file" name="logo" class="form-control" id="filer_input">
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
                </form>
            </div>
        </div><!-- end col -->
    </div>
@endsection


@section('on_page_js')
    <script>
        $(document).ready(function() {
            $('#filer_input').filer( {
                    limit: 1,
                    maxSize: 3,
                    extensions: ["jpg", "png", "gif"],
                    showThumbs: true
                }
            );
        });
    </script>

@endsection

resources/views/admin/brand/edit.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category Create')
@section('admin_content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card-box">
                <h4 class="header-title  text-center m-t-0 m-b-30"> Update Brand</h4>
                <form method="post" action="{{ route('brand.update', $brand->id) }}" enctype="multipart/form-data">
                    @method('put')
                    @csrf
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control" id="name" value="{{ $brand->name }}">
                    </div>

                    <div class="form-group">
                        <label for="filer_input">Logo</label>
                        <input type="file" name="logo" class="form-control" id="filer_input">
                        <img class="" src="{{ URL::to($brand->logo) }}" style="width:30px; height: 30px;">
                        <input  type="hidden" name="old_logo" value="{{$brand->logo}}">
                    </div>
                    <button type="submit" class="btn btn-info waves-effect waves-light">Update</button>
                </form>
            </div>
        </div><!-- end col -->
    </div>
@endsection


@section('on_page_js')
    <script>
        $(document).ready(function() {
            $('#filer_input').filer( {
                    limit: 1,
                    maxSize: 3,
                    extensions: ["jpg", "png", "gif"],
                    showThumbs: true
                }
            );
        });
    </script>

@endsection

resources/views/admin/brand/index.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category index')
@section('admin_content')

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <h4 style="display: inline-block" class="header-title m-t-0 m-b-30">Brand Index</h4>
                <button   type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light " data-toggle="modal" data-target="#category-create-modal"> Create New</button>


                <table id="datatable" class="table table-striped dt-responsive nowrap">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Logo</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($brands as $brand)
                        <tr>
                            <td>{{ $brand->id }}</td>
                            <td>{{ $brand->name }}</td>
                            <td>
                                <img class="" src="{{ URL::to($brand->logo) }}" style="width:45px; height: 25px;">

                            </td>


                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('brand.edit', $brand->id) }} ">
                                    <i class="fa fa-edit">
                                    </i>
                                </a>

                                <a href="#" class="btn btn-danger btn-xs delete-modal" data-id="{{ $brand->id }}" data-toggle="modal" data-target=".brand_delete_modal">
                                    <i id="brandName" data-id="{{ $brand->name }}" class="fa fa-trash">
                                    </i>
                                </a>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->

    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    <div id="category-create-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <form method="post" action="{{ route('brand.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"> Create Brand</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="name" class="control-label">Name</label>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="Enter brand name.." required>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="logo">Brand Logo</label>
                                    <input type="file" name="logo" class="form-control" id="logo" required>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-info waves-effect waves-light">Add</button>
                    </div>
                </div>
            </form>


        </div>
    </div><!-- /.modal -->


    <!-- Delete Modal -->



    <div class="modal fade brand_delete_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p id="category_name">
                    <form id="deleteForm" action="" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('on_page_js')
    <script>
        $(document).on("click", ".delete-modal", function () {
            let brandId = $(this).data('id');
            let brandName = $('#brandName').data('id');
            $(".modal-body #category_name").text( "Do you want to delete "+ brandName +' brand?' );
            var route = '/admin/brand/'+brandId
            $('#deleteForm').attr('action', route)
        });

    </script>
@endsection