routes/web.php
<?php

Route::get('/', function () {return view('frontend.home');});
//auth & user
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/password-change', 'HomeController@changePassword')->name('password.change');
Route::post('/password-update', 'HomeController@updatePassword')->name('password.update');
Route::get('/user/logout', 'HomeController@Logout')->name('user.logout');

//admin=======
Route::get('admin/home', 'AdminController@index')->name('admin.home');
Route::get('admin', 'Admin\LoginController@admin_login')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login')->name('admin_login.store');
// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/reset/password/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/update/reset', 'Admin\ResetPasswordController@reset')->name('admin.reset.update');
Route::get('/admin/Change/Password','AdminController@ChangePassword')->name('admin.password.change');
Route::post('/admin/password/update','AdminController@Update_pass')->name('admin.password.update');
Route::get('admin/logout', 'AdminController@logout')->name('admin.logout');

// Admin routes


//For general user
Route::get('wishlist/add/{product_id}', 'WishListController@add_wishlist')->name('wishlist.add');
Route::get('cart/add/{product_id}', 'CartController@add_cart')->name('cart.add');
Route::get('product/view-cart/', 'CartController@index')->name('cart.index');
Route::get('cart/delete/{rowId}', 'CartController@destroy')->name('cart.remove');
Route::post('cart/update', 'CartController@update')->name('cart.update');
Route::get('cart/check', 'CartController@check')->name('cart.check');
Route::get('product/checkout', 'CheckOutController@checkout')->name('checkout');
Route::post('product/checkout/store', 'CheckOutController@store')->name('checkout.store');
Route::get('product/checkout/review', 'CheckOutController@review_order')->name('checkout.review');
Route::post('product/submit-order','OrderController@order')->name('checkout.order');
Route::get('product/order/cod','OrderController@cod')->name('checkout.cod');
Route::get('product/order/paypal','OrderController@paypal')->name('checkout.paypal');
//Route::get('product/checkout', 'CartController@checkout')->name('checkout');

//For admin user
// Category
Route::prefix('admin')->group(function () {
    Route::get('category/list', 'CategoryController@index')->name('category.index');
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::post('store/category', 'CategoryController@store')->name('category.store');
    Route::post('category/{id}', 'CategoryController@delete')->name('category.delete');
    Route::get('category/edit/{id}', 'CategoryController@edit')->name('category.edit');
    Route::post('category/update/{id}', 'CategoryController@update')->name('category.update');
// Brand
    Route::resource('brand', 'BrandController');
// Sub Category
    Route::resource('subcategory', 'SubCategoryController');
// Product
    Route::resource('product', 'ProductController');
    Route::get('delete-image/{id}','ProductController@deleteImage');
// Coupon
    Route::resource('coupon', 'CouponController');
/// Product Attribute
    Route::resource('attribute','ProductAttributeController');
//Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
/// Product Images Gallery
    Route::resource('/imagegallery','ImageGalleryController');
//Route::get('delete-imageGallery/{id}','ImagesController@destroy');
//    Route::resource('wishlist', 'WishListController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{

    protected $fillable = ['title', 'sku', 'brand_id',
        'details', 'sale_price', 'quantity', 'price',
        'image', 'video_link', 'weight', 'color', 'status'];

    public function categories()
    {
        return $this->belongsToMany(Category::class)->withTimestamps();
//        return $this->belongsToMany(Category::class)->using(CategoryProduct::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function product_attributes()
    {
        return $this->hasMany(ProductAttribute::class);
    }


    public function check_category_in_pivot_by_id($id){
        return $this->categories()->firstWhere('category_id', $id);
    }

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Product;
use App\Brand;
use Image;
use Log;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $i=0;
        $products=Product::orderBy('created_at','desc')->get();
        return view('admin.product.index',compact('products','i'));    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $brands =Brand::all();
        $categories=Category::where('parent_id',0)->pluck('name','id')->all();
        return view('admin.product.create',  compact('brands', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'categories_id' => 'required|max:255',
            'title' => 'required|max:255',
            'brand_id' => 'required|max:255',
            'sku' => 'required|max:255',
            'quantity' => 'required|max:255',
            'price' => 'required|numeric',
            'image'=>'image|mimes:png,jpg,jpeg|max:1000',
        ]);

        try {
            $formInput=$request->all();
            if($request->file('image')){
                $image=$request->file('image');
                if($image->isValid()){
                    $fileName=time().'-'.str_slug($formInput['title'],"-").'.'.$image->getClientOriginalExtension();
                    $large_image_path=public_path('media/products/large/'.$fileName);
                    $medium_image_path=public_path('media/products/medium/'.$fileName);
                    $small_image_path=public_path('media/products/small/'.$fileName);
                    //Resize Image
                    Image::make($image)->save($large_image_path);
                    Image::make($image)->resize(645,807)->save($medium_image_path);
                    Image::make($image)->resize(335,405)->save($small_image_path);
                    $formInput['image']=$fileName;
                }
            }
            $product = Product::create($formInput);
            if ($product){
                $product->categories()->sync($formInput['categories_id']);
            }

            return redirect()->route('product.create')->with('message','Add Products Successfully!');

        }
        catch (\Exception $e){
            Log::error($e->getMessage());
            return redirect()->route('product.create')->with('error','Something went wrong..');

        }



    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $brands = Brand::all();
        $categories=Category::where('parent_id',0)->pluck('name','id')->all();
        $product=Product::findOrFail($id);
        $edit_categories = $product->categories;

        return view('admin.product.edit', compact('categories', 'product', 'edit_categories', 'brands'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validatedData = $request->validate([
            'categories_id' => 'required|max:255',
            'title' => 'required|max:255',
            'brand_id' => 'required|max:255',
            'sku' => 'required|max:255',
            'quantity' => 'required|max:255',
            'price' => 'required|numeric',
            'image'=>'image|mimes:png,jpg,jpeg|max:2024',
        ]);

        try {
            $update_product=Product::findOrFail($id);
            $formInput=$request->all();
            if($update_product['image']==''){
                if($request->file('image')){
                    $image=$request->file('image');
                    if($image->isValid()){
                        $fileName=time().'-'.str_slug($formInput['title'],"-").'.'.$image->getClientOriginalExtension();
                        $large_image_path=public_path('media/products/large/'.$fileName);
                        $medium_image_path=public_path('media/products/medium/'.$fileName);
                        $small_image_path=public_path('media/products/small/'.$fileName);
                        //Resize Image
                        Image::make($image)->save($large_image_path);
                        Image::make($image)->resize(600,600)->save($medium_image_path);
                        Image::make($image)->resize(300,300)->save($small_image_path);
                        $formInput['image']=$fileName;
                    }
                }
            }else{
                $formInput['image']=$update_product['image'];
            }

            $update_product->update($formInput);
            if ($update_product){
                $update_product->categories()->sync($formInput['categories_id']);
            }
            $notification=array(
                'message'=>"Product updated",
                'alert-type'=>'success'
            );
            return redirect()->route('product.index')->with($notification);
        }
    catch (\Exception $e){
            Log::error($e->getMessage());
//        dd($formInput=$request->all());

        $notification=array(
            'message'=>"Product doesn't updated",
            'alert-type'=>'error'
        );
        dd($notification);
        return redirect()->route('product.edit', $update_product->id)->with($notification);

    }

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {


        try {
            $delete_product=Product::findOrFail($id);
            $image_large=public_path().'/media/products/large/'.$delete_product->image;
            $image_medium=public_path().'/media/products/medium/'.$delete_product->image;
            $image_small=public_path().'/media/products/small/'.$delete_product->image;

            $delete_product->categories()->detach();
            $delete_product->delete();
            $notification=array(
                'message'=>"Product deleted",
                'alert-type'=>'error'
            );

            return Redirect()->back()->with($notification);
        }

        catch (\Exception $e) {
            Log::error($e->getMessage());
            $notification=array(
                'message'=>"Product doesn't deleted",
                'alert-type'=>'error'
            );

            return Redirect()->back()->with($notification);
        }

    }



    public function deleteImage($id){
        //Products_model::where(['id'=>$id])->update(['image'=>'']);
        $product=Product::findOrFail($id);
        $image_large=public_path().'/media/products/large/'.$product->image;
        $image_medium=public_path().'/media/products/medium/'.$product->image;
        $image_small=public_path().'/media/products/small/'.$product->image;
        if($product){
            $product->image='';
            $product->save();
            ////// delete image ///
            unlink($image_large);
            unlink($image_medium);
            unlink($image_small);
        }
        return back();
    }
}

resources/views/admin/product/add_image_gallery.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category index')
@section('admin_content')

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->

    <div class="row">
        <div class="col-sm-6">
            <div class="card-box">
                <h4 style="display: inline-block" class="header-title">Product: {{ $product->title }}</h4>
                <table class="table m-0">
                    <tbody>
                    <tr>
                        <td>
                            <img src="{{url('media/products/small',$product->image)}}" alt="" width="40" height="40">
                            <div style="display: inline-block">
                                <span>Product Code : <b>{{$product->sku}}</b></span>
                                <p>Product Status : <b>{{$product->status? 'Active': 'Inactive' }}</b></p>
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td>
                                <form action="{{route('imagegallery.store')}}" method="post" role="form" enctype="multipart/form-data">
                                    <legend>Can Add Multi Images</legend>
                                    @csrf
                                    <div class="form-group">
                                        <input type="hidden" name="product_id" value="{{$product->id}}">
                                        <input type="file" name="image[]" id="id_imageGallery" class="form-control" multiple="multiple" required>
                                        <span class="text-danger d-flex">{{$errors->first('image')}}</span>
                                        <button type="submit" class="btn btn-success">Upload</button>
                                    </div>
                                </form>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="card-box table-responsive text-center">
                <h4 style="display: inline-block" class="display-4">Images List</h4>
                {{--                <hr>--}}
                {{--                <button   type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light " data-toggle="modal" data-target="#category-create-modal"> Create New</button>--}}
                <table id="alignMiddleTable" class="table table-bordered ">
                    <thead>
                    <tr >
                        <th>Id#</th>
                        <th class="text-center">Image</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>

                    <tbody class="text-center">
                    @foreach($image_aglleries as $img_gallery)
                        <?php $i++; ?>
                        <tr>
                            <th scope="row">{{$i}}</th>
                            <td><img src="{{url('media/products/small',$img_gallery->image)}}" class="img-responsive" alt="Image" width="60"></td>
                            <td>
                                <a href="#" class="btn btn-danger btn-xs delete-modal" data-id="{{ $img_gallery->id }}" data-toggle="modal" data-target=".img_delete_modal">
                                    <i id="product_title" data-id="{{ $img_gallery->image }}" class="fa fa-trash">
                                    </i>
                                </a>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div><!-- end col -->



    </div>
    <!-- end row -->

    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    {{--    <div id="category-create-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">--}}
    {{--        <div class="modal-dialog">--}}
    {{--            <form method="post" action="{{ route('category.store') }}">--}}
    {{--                @csrf--}}
    {{--                <div class="modal-content">--}}
    {{--                    <div class="modal-header">--}}
    {{--                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
    {{--                        <h4 class="modal-title"> Create Category</h4>--}}
    {{--                    </div>--}}
    {{--                    <div class="modal-body">--}}
    {{--                        <div class="row">--}}
    {{--                            <div class="col-md-12">--}}
    {{--                                <div class="form-group">--}}
    {{--                                    <label for="name" class="control-label">Name</label>--}}
    {{--                                    <input type="text" class="form-control" name="name" id="name" placeholder="Enter category name.." required>--}}
    {{--                                </div>--}}
    {{--                            </div>--}}
    {{--                        </div>--}}
    {{--                    </div>--}}
    {{--                    <div class="modal-footer">--}}
    {{--                        <button type="submit" class="btn btn-info waves-effect waves-light">Add</button>--}}
    {{--                    </div>--}}
    {{--                </div>--}}
    {{--            </form>--}}


    {{--        </div>--}}
    {{--    </div><!-- /.modal -->--}}


    <!-- Delete Modal -->
    <div class="modal fade img_delete_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p id="category_name">
                    <form id="deleteForm" action="" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('on_page_js')
    <script>
        $(document).on("click", ".delete-modal", function () {
            let imageID = $(this).data('id');
            let product_title = $('#product_title').data('id');
            console.log(imageID);
            console.log(product_title);
            $(".modal-body #category_name").text( "Do you want to delete "+ product_title +' image?' );
            var route = '/admin/imagegallery/'+imageID
            $('#deleteForm').attr('action', route)
        });

    </script>
    <script>

        $(document).ready(function() {
            $('#id_imageGallery').filer( {
                    limit:10,
                    maxSize: 3,
                    extensions: ["jpg", "png", "gif", 'jpeg'],
                    showThumbs: true
                }
            );
        });
        // Select2
        $(".select2").select2();
    </script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.admin_layouts')
@section('title', 'Product index')
@section('admin_content')

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <h4 style="display: inline-block" class="header-title m-t-0 m-b-30">Product Index</h4>
                <a href="{{ route('product.create') }}">
                    <button   type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light "> Create New</button>

                </a>


                <table id="datatable" class="table table-striped dt-responsive nowrap">
                    <thead>
                    <tr>
                        <th>Id#</th>
                        <th>Image</th>
                        <th>Title</th>
                        <th>Categories</th>
                        <th>Brand</th>
                        <th>Sku</th>
                        <th>Price</th>
                        <th>SalePrice</th>
                        <th>Status</th>
                        <th> Attribute</th>
                        <th>ImageGallery</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($products as $product)
                        <?php $i++; ?>
                        <tr>
                            <td>{{$i}}</td>
                            <td><img src="{{url('media/products/large',$product->image)}}" alt="" width="25" height="25"></td>
                            <td class="text-center">{{ $product->title }}</td>
                            <td class="text-center">
                                @foreach( $product->categories as $category)
                                    <li> {{ isset($category->name) ? $category->name: 'Product has no category' }}</li>
                                @endforeach
                            </td>
                            <td class="text-center">{{ is_object($product->brand)? $product->brand->name: '--' }}</td>
                            <td class="text-center">{{ $product->sku }}</td>
                            <td class="text-center">{{ $product->price }}</td>
                            <td class="text-center">{{ $product->sale_price }}</td>
                            <td class="text-center">{{ $product->status == 1? 'Published': 'Unpublished' }}</td>
                            <td class="text-center">
                                <a href="{{route('attribute.show',$product->id)}}" class="btn btn-success btn-xs">Add Attribute</a>
                            </td>
                            <td class="text-center">
                                <a  href="{{route('imagegallery.show',$product->id)}}" class="btn btn-primary btn-xs" >Add Images</a>
                            </td>

                            <td class="text-center">
                                <a class="btn btn-primary btn-xs" href="{{ route('product.edit', $product->id) }} ">
                                    <i class="fa fa-edit">
                                    </i>
                                </a>

                                <a href="#" class="btn btn-danger btn-xs delete-modal" data-id="{{ $product->id }}" data-toggle="modal" data-target=".product_delete_modal">
                                    <i id="product_title" data-id="{{ $product->title }}" class="fa fa-trash">
                                    </i>
                                </a>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->

    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


{{--    <div id="coupon-create-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">--}}
{{--        <div class="modal-dialog">--}}
{{--            <form method="post" action="{{ route('coupon.store') }}">--}}
{{--                @csrf--}}
{{--                <div class="modal-content">--}}
{{--                    <div class="modal-header">--}}
{{--                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
{{--                        <h4 class="modal-title"> Create coupon</h4>--}}
{{--                    </div>--}}
{{--                    <div class="modal-body">--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="name">Coupon code</label>--}}
{{--                            <input type="text" name="code" class="form-control" id="categoryName" placeholder="Enter unique coupon code">--}}
{{--                        </div>--}}

{{--                        <div class="form-group">--}}
{{--                            <label for="type"> Coupon Type</label>--}}
{{--                            <select id="type" class="form-control" name="type"  onchange="changeFunc();">--}}
{{--                                <option class="text-muted" value="" >--Select Coupon Type--</option>--}}
{{--                                <option value="1">Fixed</option>--}}
{{--                                <option value="2">Percent</option>--}}
{{--                            </select>--}}
{{--                        </div>--}}
{{--                        <div class="form-group">--}}
{{--                            <input style="display: none" type="text" name="value" class="form-control"  id="fixedValue" placeholder="Enter fixed discount value">--}}
{{--                        </div>--}}

{{--                        <div class="form-group">--}}
{{--                            <input style="display: none" type="text" name="percent_of" class="form-control"  id="percentOf" placeholder="Enter percent value">--}}
{{--                        </div>--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="status">Status</label>--}}
{{--                            <select class="form-control" name="status" id="status" required>--}}
{{--                                <option class="text-muted" value="" >--Select Status--</option>--}}
{{--                                <option value="1">Active</option>--}}
{{--                                <option value="2">Inactive</option>--}}
{{--                            </select>--}}
{{--                        </div>--}}
{{--                        <button type="submit" class="btn btn-info">Save</button>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </form>--}}


{{--        </div>--}}
{{--    </div><!-- /.modal -->--}}


    <!-- Delete Modal -->



    <div class="modal fade product_delete_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p id="product_title">
                    <form id="deleteForm" action="" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('on_page_js')


    <script>
        function changeFunc() {
            var selectBox = document.getElementById("type");
            var selectedValue = selectBox.options[selectBox.selectedIndex].value;
            if (selectedValue=="1"){
                $('#fixedValue').show();
                $('#percentOf').hide();
            }
            else if (selectedValue=="2") {
                $('#percentOf').show();
                $('#fixedValue').hide();

            }
            else {
                alert("Select a valid option");
                $('#percentOf').hide();
                $('#fixedValue').hide();            }
        }
    </script>
    <script>
        $(document).on("click", ".delete-modal", function () {
            let productId = $(this).data('id');
            let product_title = $('#product_title').data('id');
            $(".modal-body #product_title").text( "Do you want to delete "+ product_title +' coupon?' );
            var route = '/admin/product/'+productId
            $('#deleteForm').attr('action', route)
        });
    </script>

{{--    <script>--}}
{{--        $(document).ready(function() {--}}
{{--            $('#datatable').dataTable();--}}
{{--            $('#datatable-keytable').DataTable( { keys: true } );--}}
{{--            $('#datatable-responsive').DataTable();--}}
{{--            $('#datatable-scroller').DataTable( { ajax: "assets/plugins/datatables/json/scroller-demo.json", deferRender: true, scrollY: 380, scrollCollapse: true, scroller: true } );--}}
{{--            var table = $('#datatable-fixed-header').DataTable( { fixedHeader: true } );--}}
{{--        } );--}}
{{--        TableManageButtons.init();--}}
{{--    </script>--}}
@endsection