routes/web.php
<?php

Route::get('/', function () {return view('frontend.home');});
//auth & user
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/password-change', 'HomeController@changePassword')->name('password.change');
Route::post('/password-update', 'HomeController@updatePassword')->name('password.update');
Route::get('/user/logout', 'HomeController@Logout')->name('user.logout');

//admin=======
Route::get('admin/home', 'AdminController@index')->name('admin.home');
Route::get('admin', 'Admin\LoginController@admin_login')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login')->name('admin_login.store');
// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/reset/password/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/update/reset', 'Admin\ResetPasswordController@reset')->name('admin.reset.update');
Route::get('/admin/Change/Password','AdminController@ChangePassword')->name('admin.password.change');
Route::post('/admin/password/update','AdminController@Update_pass')->name('admin.password.update');
Route::get('admin/logout', 'AdminController@logout')->name('admin.logout');

// Admin routes


//For general user
Route::get('wishlist/add/{product_id}', 'WishListController@add_wishlist')->name('wishlist.add');
Route::get('cart/add/{product_id}', 'CartController@add_cart')->name('cart.add');
Route::get('product/view-cart/', 'CartController@index')->name('cart.index');
Route::get('cart/delete/{rowId}', 'CartController@destroy')->name('cart.remove');
Route::post('cart/update', 'CartController@update')->name('cart.update');
Route::get('cart/check', 'CartController@check')->name('cart.check');
Route::get('product/checkout', 'CheckOutController@checkout')->name('checkout');
Route::post('product/checkout/store', 'CheckOutController@store')->name('checkout.store');
Route::get('product/checkout/review', 'CheckOutController@review_order')->name('checkout.review');
Route::post('product/submit-order','OrderController@order')->name('checkout.order');
Route::get('product/order/cod','OrderController@cod')->name('checkout.cod');
Route::get('product/order/paypal','OrderController@paypal')->name('checkout.paypal');
//Route::get('product/checkout', 'CartController@checkout')->name('checkout');

//For admin user
// Category
Route::prefix('admin')->group(function () {
    Route::get('category/list', 'CategoryController@index')->name('category.index');
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::post('store/category', 'CategoryController@store')->name('category.store');
    Route::post('category/{id}', 'CategoryController@delete')->name('category.delete');
    Route::get('category/edit/{id}', 'CategoryController@edit')->name('category.edit');
    Route::post('category/update/{id}', 'CategoryController@update')->name('category.update');
// Brand
    Route::resource('brand', 'BrandController');
// Sub Category
    Route::resource('subcategory', 'SubCategoryController');
// Product
    Route::resource('product', 'ProductController');
    Route::get('delete-image/{id}','ProductController@deleteImage');
// Coupon
    Route::resource('coupon', 'CouponController');
/// Product Attribute
    Route::resource('attribute','ProductAttributeController');
//Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
/// Product Images Gallery
    Route::resource('/imagegallery','ImageGalleryController');
//Route::get('delete-imageGallery/{id}','ImagesController@destroy');
//    Route::resource('wishlist', 'WishListController');
});

resources/views/admin/__partials/css_asset_link.blade.php
<!-- file upload  -->

<link href="{{ asset('backend/plugins/jquery.filer/css/jquery.filer.css') }}" rel="stylesheet" />
<link href="{{ asset('backend/plugins/jquery.filer/css/themes/jquery.filer-dragdropbox-theme.css') }}" rel="stylesheet" />

<!-- DataTables -->
<link href="{{ asset('backend/plugins/datatables/jquery.dataTables.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/plugins/datatables/buttons.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href=" {{ asset('backend/plugins/datatables/fixedHeader.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href=" {{ asset('backend/plugins/datatables/responsive.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href=" {{ asset('backend/plugins/datatables/scroller.bootstrap.min.css') }}" rel="stylesheet" type="text/css" />

<!-- Core js -->
<link rel="stylesheet" href="{{ asset('backend/plugins/morris/morris.css') }}">
<link href="{{ asset('backend/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/menu.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/core.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/components.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/icons.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/pages.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/css/responsive.css') }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('backend/js/modernizr.min.js') }}"></script>
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','../../../www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-77043005-1', 'auto');
    ga('send', 'pageview');

</script>

<!-- select2, multiple select -->

<link href="{{ asset('backend/plugins/summernote/summernote.css') }}" rel="stylesheet" />
<link href="{{ asset('backend/plugins/multiselect/css/multi-select.css') }}"  rel="stylesheet" type="text/css" />
<link href="{{ asset('backend/plugins/select2/dist/css/select2.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('backend/plugins/select2/dist/css/select2-bootstrap.css') }}" rel="stylesheet" type="text/css">
<link href="{{ asset('backend/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css') }}" rel="stylesheet" />
<link href="{{ asset('css/custom.css') }}" rel="stylesheet" />
<!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
{{--    <script src="{{ asset('https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js') }}"></script>--}}
{{--    <script src="{{ asset('https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js') }}"></script>--}}
    <![endif]-->
<!-- For tag input -->
{{--<link href="{{asset('backend/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.css')}}" rel="stylesheet" />--}}
<!-- Summer Note Design -->
{{--<link href="{{ asset('backend/plugins/summernote/summernote.css') }}" rel="stylesheet" />--}}


<!-- Material Design -->
{{--<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">--}}

resources/views/admin/__partials/js_asset_link.blade.php
<script>
    var resizefunc = [];
</script>

<!-- jQuery  -->
<script src="{{ asset('backend/js/jquery.min.js') }}"></script>
<script src="{{ asset('backend/js/bootstrap.min.js') }}"></script>
<script src="{{ assert('backend/js/detect.js') }}"></script>
<script src="{{ asset('backend/js/fastclick.js') }}"></script>
<script src="{{ asset('backend/js/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('backend/js/jquery.blockUI.js') }}"></script>
<script src="{{ asset('backend/js/waves.js') }}"></script>
<script src="{{ asset('backend/js/wow.min.js') }}"></script>
<script src="{{ asset('backend/js/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('backend/js/jquery.scrollTo.min.js') }}"></script>



<!-- Datatables -->
<script src="{{ asset('backend/plugins/datatables/jquery.dataTables.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/buttons.bootstrap.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/dataTables.fixedHeader.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/dataTables.responsive.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/dataTables.bootstrap.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/dataTables.buttons.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/jszip.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/pdfmake.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/vfs_fonts.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/buttons.html5.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/buttons.print.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/dataTables.keyTable.min.js') }}"></script>
<script src=" {{ asset('backend/plugins/datatables/responsive.bootstrap.min.js') }}"></script>

<!-- Datatable init js -->
<script src=" {{ asset('backend/pages/jquery.datatables.init.js') }}"></script>

{{--<!-- Tag input js -->--}}
{{--<script src="{{asset('backend/plugins/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js')}}"></script>--}}

{{--<!-- isotope plugin js -->--}}
{{--<script src="{{ asset('backend/plugins/isotope/js/isotope.pkgd.min.js') }}"></script>--}}

{{--<script src="{{ asset('backend/js/jquery.core.js') }}"></script>--}}
{{--<script src="{{ asset('backend/js/jquery.app.js') }}"></script>--}}
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

<script src="{{ asset('https://unpkg.com/sweetalert/dist/sweetalert.min.js')}}"></script>

{{--<script src="{{ asset('backend/plugins/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>--}}
{{--<script type="text/javascript" src="{{ asset('backend/plugins/multiselect/js/jquery.multi-select.js') }}"></script>--}}

{{--<script src="{{ assert('backend/plugins/jquery.filer/js/jquery.filer.min.js') }}"></script>--}}



{{--<script type="text/javascript">--}}
{{--    $(window).load(function(){--}}
{{--        var $container = $('.masonry-container');--}}
{{--        $container.isotope({--}}
{{--            filter: '*'--}}
{{--        });--}}
{{--    });--}}
{{--</script>--}}

<!-- Data table -->
<script type="text/javascript">
    $(document).ready(function() {
        $('#datatable').dataTable();
        $('#datatable-keytable').DataTable( { keys: true } );
        $('#datatable-responsive').DataTable();
        $('#datatable-scroller').DataTable( { ajax: "backend/plugins/datatables/json/scroller-demo.json", deferRender: true, scrollY: 380, scrollCollapse: true, scroller: true } );
        var table = $('#datatable-fixed-header').DataTable( { fixedHeader: true } );
    } );
    TableManageButtons.init();
</script>




<!-- Jquery filer js -->
<script src="{{ asset('backend/plugins/jquery.filer/js/jquery.filer.min.js') }}"></script>
<!-- App js -->
<script src="{{ asset('backend/js/jquery.core.js') }}"></script>
<script src="{{ asset('backend/js/jquery.app.js') }}"></script>

<!-- page specific js -->
<script src="{{ asset('backend/pages/jquery.fileuploads.init.js') }}"></script>


<script src="{{ asset('backend/plugins/summernote/summernote.min.js') }}"></script>
<script src="{{ asset('backend/plugins/multiselect/js/jquery.multi-select.js') }}"></script>
<script src="{{ asset('backend/plugins/jquery-quicksearch/jquery.quicksearch.js') }}"></script>
<script src="{{ asset('backend/plugins/select2/dist/js/select2.min.js') }}" type="text/javascript"></script>


<script>
    @if(Session::has('message'))
    var type="{{Session::get('alert-type','info')}}"
    switch(type){
        case 'info':
            toastr.info("{{ Session::get('message') }}");
            break;
        case 'success':
            toastr.success("{{ Session::get('message') }}");
            break;
        case 'warning':
            toastr.warning("{{ Session::get('message') }}");
            break;
        case 'error':
            toastr.error("{{ Session::get('message') }}");
            break;
    }
    @endif
</script>

@yield('on_page_js')

resources/views/admin/__partials/notification.blade.php
<!-- Right Sidebar -->
<div class="side-bar right-bar">
    <a href="javascript:void(0);" class="right-bar-toggle">
        <i class="zmdi zmdi-close-circle-o"></i>
    </a>
    <h4 class="">Notifications</h4>
    <div class="notification-list nicescroll">
        <ul class="list-group list-no-border user-list">
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="{{ asset('backend/images/users/avatar-2.jpg') }}" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">Michael Zenaty</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-account"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Signup</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">5 hours ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-comment"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">New Message received</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item">
                <a href="#" class="user-list-item">
                    <div class="avatar">
                        <img src="{{ asset('backend/images/users/avatar-3.jpg') }}" alt="">
                    </div>
                    <div class="user-desc">
                        <span class="name">James Anderson</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">2 days ago</span>
                    </div>
                </a>
            </li>
            <li class="list-group-item active">
                <a href="#" class="user-list-item">
                    <div class="icon">
                        <i class="zmdi zmdi-settings"></i>
                    </div>
                    <div class="user-desc">
                        <span class="name">Settings</span>
                        <span class="desc">There are new settings available</span>
                        <span class="time">1 day ago</span>
                    </div>
                </a>
            </li>

        </ul>
    </div>
</div>

<!-- /Right-bar -->

resources/views/admin/__partials/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->

<div class="left side-menu">
    <div class="sidebar-inner slimscrollleft">
        <!--- Divider -->
        <div id="sidebar-menu">
            <ul>

                <li class="text-muted menu-title">Navigation</li>

                <li class="has_sub">
                    <a href="{{ route('admin.home') }}" class="waves-effect"><i class="fa fa-home"></i>
                        <span> Dashboard </span> </a>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect">
                        <i class="fa fa-indent"></i>

                        <span> Category </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('category.index') }}">List</a></li>
                        <li><a href="{{ route('category.create') }}">Create</a></li>
                    </ul>
                </li>
                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-check-circle-o" aria-hidden="true"></i>
                        <span> Brand </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('brand.index') }}">List</a></li>
                        <li><a href="{{ route('brand.create') }}">Create</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-product-hunt" aria-hidden="true"></i>

                        <span> Product </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('product.index') }}">List</a></li>
                        <li><a href="{{ route('product.create') }}">Create</a></li>
                    </ul>
                </li>

                <li class="has_sub">
                    <a href="javascript:void(0);" class="waves-effect"><i class="fa fa-tags"></i>
                        <span> Coupon </span> <span class="menu-arrow"></span> </a>
                    <ul class="list-unstyled">
                        <li><a href="{{ route('coupon.index') }}">List</a></li>
                        <li><a href="{{ route('coupon.create') }}">Create</a></li>
                    </ul>
                </li>




{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> SubCategory </span> <span class="menu-arrow"></span> </a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="ui-buttons.html">Buttons</a></li>--}}
{{--                        <li><a href="ui-cards.html">Cards</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> Brand </span> <span class="menu-arrow"></span> </a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="ui-buttons.html">Buttons</a></li>--}}
{{--                        <li><a href="ui-cards.html">Cards</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}


{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-invert-colors"></i> <span> User Interface </span> <span class="menu-arrow"></span> </a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="ui-buttons.html">Buttons</a></li>--}}
{{--                        <li><a href="ui-cards.html">Cards</a></li>--}}
{{--                        <li><a href="ui-typography.html">Typography </a></li>--}}
{{--                        <li><a href="ui-checkbox-radio.html">Checkboxs-Radios</a></li>--}}
{{--                        <li><a href="ui-icons.html">Icons</a></li>--}}
{{--                        <li><a href="ui-modals.html">Modals</a></li>--}}
{{--                        <li><a href="ui-images.html">Images</a></li>--}}
{{--                        <li><a href="ui-components.html">Components</a>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-case"></i> <span> Admin UI </span> <span class="menu-arrow"></span> </a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="admin-masonry.html">Masonry</a></li>--}}
{{--                        <li><a href="admin-notification.html">Notification</a></li>--}}
{{--                        <li><a href="admin-range-slider.html">Range Slider</a></li>--}}
{{--                        <li><a href="admin-sweetalert.html">Sweet Alert</a>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="widgets.html" class="waves-effect"><i class="zmdi zmdi-layers"></i> <span> Widgets </span> </a>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-text"></i><span class="label label-default pull-right">6</span><span> Forms </span> </a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="form-elements.html">Form Elements</a></li>--}}
{{--                        <li><a href="form-advanced.html">Advanced Form</a></li>--}}
{{--                        <li><a href="form-validation.html">Form Validation</a></li>--}}
{{--                        <li><a href="form-wizard.html">Form Wizard</a></li>--}}
{{--                        <li><a href="form-summernote.html">Summernote</a></li>--}}
{{--                        <li><a href="form-uploads.html">Form Uploads</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-view-list"></i> <span> Tables </span> <span class="menu-arrow"></span></a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="tables-basic.html">Basic Tables</a></li>--}}
{{--                        <li><a href="tables-datatable.html">Data Table</a></li>--}}
{{--                        <li><a href="tables-editable.html">Editable Table</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-chart"></i><span> Charts </span> <span class="menu-arrow"></span></a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="chart-flot.html">Flot Chart</a></li>--}}
{{--                        <li><a href="chart-morris.html">Morris Chart</a></li>--}}
{{--                        <li><a href="chart-chartist.html">Chartist Charts</a></li>--}}
{{--                        <li><a href="chart-other.html">Other Chart</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-map"></i><span> Maps </span> <span class="menu-arrow"></span></a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="map-google.html">Google Maps</a></li>--}}
{{--                        <li><a href="map-vector.html">Vector Maps</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="text-muted menu-title">More</li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="zmdi zmdi-collection-item"></i><span class="label label-default pull-right">8</span><span> Pages </span></a>--}}
{{--                    <ul class="list-unstyled">--}}
{{--                        <li><a href="page-starter.html">Starter Page</a></li>--}}
{{--                        <li><a href="page-timeline.html">Timeline</a></li>--}}
{{--                        <li><a href="page-login.html">Login</a></li>--}}
{{--                        <li><a href="page-register.html">Register</a></li>--}}
{{--                        <li><a href="page-recoverpw.html">Recover Password</a></li>--}}
{{--                        <li><a href="page-lock-screen.html">Lock Screen</a></li>--}}
{{--                        <li><a href="page-confirm-mail.html">Confirm Mail</a></li>--}}
{{--                        <li><a href="page-404.html">Error 404</a></li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

{{--                <li class="has_sub">--}}
{{--                    <a href="javascript:void(0);" class="waves-effect"><i class="ti-share"></i><span> Multi Level </span> <span class="menu-arrow"></span></a>--}}
{{--                    <ul>--}}
{{--                        <li class="has_sub">--}}
{{--                            <a href="javascript:void(0);" class="waves-effect"><span>Menu Level 1.1</span> <span class="menu-arrow"></span></a>--}}
{{--                            <ul style="">--}}
{{--                                <li><a href="javascript:void(0);"><span>Menu Level 2.1</span></a></li>--}}
{{--                                <li><a href="javascript:void(0);"><span>Menu Level 2.2</span></a></li>--}}
{{--                                <li><a href="javascript:void(0);"><span>Menu Level 2.3</span></a></li>--}}
{{--                            </ul>--}}
{{--                        </li>--}}
{{--                        <li>--}}
{{--                            <a href="javascript:void(0);"><span>Menu Level 1.2</span></a>--}}
{{--                        </li>--}}
{{--                    </ul>--}}
{{--                </li>--}}

            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>

    </div>
</div>
<!-- Left Sidebar End -->

resources/views/admin/__partials/topbar.blade.php
<!-- Top Bar Start -->
<div class="topbar">

    <!-- LOGO -->
    <div class="topbar-left">
        <div class="text-center">
            <a href="{{route('admin.home')}}" class="logo">
                <i class="zmdi zmdi-toys icon-c-logo"></i><span>ModiPonno</span>
                <!--<span><img src="assets/images/logo.png" alt="logo" style="height: 20px;"></span>-->
            </a>
        </div>
    </div>

    <!-- Button mobile view to collapse sidebar menu -->
    <div class="navbar navbar-default" role="navigation">
        <div class="container">
            <div class="">
                <div class="pull-left">
                    <button class="button-menu-mobile open-left waves-effect waves-light">
                        <i class="zmdi zmdi-menu"></i>
                    </button>
                    <span class="clearfix"></span>
                </div>

                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                    <input type="text" placeholder="Search..." class="form-control">
                    <a href="#"><i class="fa fa-search"></i></a>
                </form>


                <ul class="nav navbar-nav navbar-right pull-right">
                    <li>
                        <!-- Notification -->
                        <div class="notification-box">
                            <ul class="list-inline m-b-0">
                                <li>
                                    <a href="javascript:void(0);" class="right-bar-toggle">
                                        <i class="zmdi zmdi-notifications-none"></i>
                                    </a>
                                    <div class="noti-dot">
                                        <span class="dot"></span>
                                        <span class="pulse"></span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!-- End Notification bar -->
                    </li>

                    <li class="dropdown user-box">
                        <a href="#" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                            <img src="{{ asset('backend/images/users/avatar-1.jpg') }}" alt="user-img" class="img-circle user-img">
                            <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
                        </a>

                        <ul class="dropdown-menu">
                            <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                            <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
                            <li><a href="{{route('admin.logout')}}"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                        </ul>
                    </li>
                </ul>

            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
</div>
<!-- Top Bar End -->