routes/web.php
<?php

Route::get('/', function () {return view('frontend.home');});
//auth & user
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/password-change', 'HomeController@changePassword')->name('password.change');
Route::post('/password-update', 'HomeController@updatePassword')->name('password.update');
Route::get('/user/logout', 'HomeController@Logout')->name('user.logout');

//admin=======
Route::get('admin/home', 'AdminController@index')->name('admin.home');
Route::get('admin', 'Admin\LoginController@admin_login')->name('admin.login');
Route::post('admin', 'Admin\LoginController@login')->name('admin_login.store');
// Password Reset Routes...
Route::get('admin/password/reset', 'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/email', 'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin/reset/password/{token}', 'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/update/reset', 'Admin\ResetPasswordController@reset')->name('admin.reset.update');
Route::get('/admin/Change/Password','AdminController@ChangePassword')->name('admin.password.change');
Route::post('/admin/password/update','AdminController@Update_pass')->name('admin.password.update');
Route::get('admin/logout', 'AdminController@logout')->name('admin.logout');

// Admin routes


//For general user
Route::get('wishlist/add/{product_id}', 'WishListController@add_wishlist')->name('wishlist.add');
Route::get('cart/add/{product_id}', 'CartController@add_cart')->name('cart.add');
Route::get('product/view-cart/', 'CartController@index')->name('cart.index');
Route::get('cart/delete/{rowId}', 'CartController@destroy')->name('cart.remove');
Route::post('cart/update', 'CartController@update')->name('cart.update');
Route::get('cart/check', 'CartController@check')->name('cart.check');
Route::get('product/checkout', 'CheckOutController@checkout')->name('checkout');
Route::post('product/checkout/store', 'CheckOutController@store')->name('checkout.store');
Route::get('product/checkout/review', 'CheckOutController@review_order')->name('checkout.review');
Route::post('product/submit-order','OrderController@order')->name('checkout.order');
Route::get('product/order/cod','OrderController@cod')->name('checkout.cod');
Route::get('product/order/paypal','OrderController@paypal')->name('checkout.paypal');
//Route::get('product/checkout', 'CartController@checkout')->name('checkout');

//For admin user
// Category
Route::prefix('admin')->group(function () {
    Route::get('category/list', 'CategoryController@index')->name('category.index');
    Route::get('category/create', 'CategoryController@create')->name('category.create');
    Route::post('store/category', 'CategoryController@store')->name('category.store');
    Route::post('category/{id}', 'CategoryController@delete')->name('category.delete');
    Route::get('category/edit/{id}', 'CategoryController@edit')->name('category.edit');
    Route::post('category/update/{id}', 'CategoryController@update')->name('category.update');
// Brand
    Route::resource('brand', 'BrandController');
// Sub Category
    Route::resource('subcategory', 'SubCategoryController');
// Product
    Route::resource('product', 'ProductController');
    Route::get('delete-image/{id}','ProductController@deleteImage');
// Coupon
    Route::resource('coupon', 'CouponController');
/// Product Attribute
    Route::resource('attribute','ProductAttributeController');
//Route::get('delete-attribute/{id}','ProductAtrrController@deleteAttr');
/// Product Images Gallery
    Route::resource('/imagegallery','ImageGalleryController');
//Route::get('delete-imageGallery/{id}','ImagesController@destroy');
//    Route::resource('wishlist', 'WishListController');
});

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
  protected $fillable = ['category_id', 'name'];


    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/Http/Controllers/SubCategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\SubCategory;
use Illuminate\Http\Request;

use Illuminate\Support\Facades\DB;

class SubCategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth:admin');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {


        $data =  array();
        $data['subcategories']  =  SubCategory::all();
        $data['categories']     =  Category::all();

        return view('admin.sub_category.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories = Category::all();

        return view('admin.sub_category.create')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store (Request $request){
        $validatedData = $request->validate([
            'name' => 'required|unique:sub_categories|max:255',
            'category_id' => 'required|max:255',
        ]);

        try{
            $sub_category = new SubCategory();
            $sub_category->name = $request['name'];
            $sub_category->category_id = $request['category_id'];
            $sub_category->save();

            $notification=array(
                'message'=>'Sub Category created successfully',
                'alert-type'=>'success'
            );

            return Redirect()->route('subcategory.index')->with($notification);
        }
        catch(Exception $e){
            $notification=array(
                'message'=>"Sub Category doesn't created",
                'alert-type'=>'error'
            );
            return Redirect()->back()->with($notification);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategory = SubCategory::where('id', $id)->first();
        return view('admin.sub_category.edit')->withSubcategory($subcategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {



        try{
            $validatedData = $request->validate([
                'name' => 'required|unique:categories|max:255',
            ]);

            $sub_category = SubCategory::where('id', $id)->first();
            $sub_category->name = $request['name'];
            $update = $sub_category->save();

            $notification=array(
                'message'=>"Sub Category updated successfully",
                'alert-type'=>'success'
            );

            return redirect('admin/subcategory')->with($notification);
        }
        catch(Exception $e){
            $notification=array(
                'message'=>"Sub Category doesn't updated",
                'alert-type'=>'error'
            );

            return Redirect()->back()->with($notification);

        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategory = SubCategory::where('id', $id)->first();
        $subcategory->delete();
        $notification=array(
            'message'=>"Sub category deleted",
            'alert-type'=>'success'
        );
        return Redirect()->back()->with($notification);
    }
}

resources/views/admin/sub_category/create.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category Create')
@section('admin_content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card-box">
                <h4 class="header-title  text-center m-t-0 m-b-30"> Add Sub Category</h4>
                <form method="post" action="{{ route('subcategory.store') }}">
                    @csrf
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="category_id"> Category</label>
                                <select class="form-control" name="category_id" id="category_id">
                                    <option value="">--Select a category--</option>
                                @foreach($categories as $category)
                                        <option value="{{$category->id}}"> {{ $category->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label for="name">Sub Category Name</label>
                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter SubCategory Name">
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-info waves-effect waves-light">Save</button>
                </form>
            </div>
        </div><!-- end col -->
    </div>
@endsection



{{--<div id="category-create-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">--}}
{{--    <div class="modal-dialog">--}}
{{--        <form method="post" action="{{ route('subcategory.store') }}">--}}
{{--            @csrf--}}
{{--            <div class="modal-content">--}}
{{--                <div class="modal-header">--}}
{{--                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>--}}
{{--                    <h4 class="modal-title"> Sub Category Add</h4>--}}
{{--                </div>--}}
{{--                <div class="modal-body">--}}
{{--                    <div class="row">--}}
{{--                        <div class="col-md-12">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="name"> Category</label>--}}
{{--                                <select class="form-control" name="category_id">--}}
{{--                                    @foreach($data['categories'] as $category)--}}
{{--                                        <option value="{{$category->id}}"> {{ $category->name }}</option>--}}
{{--                                    @endforeach--}}
{{--                                </select>--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                    <div class="row">--}}
{{--                        <div class="col-md-12">--}}
{{--                            <div class="form-group">--}}
{{--                                <label for="name">Sub Category Name</label>--}}
{{--                                <input type="text" name="name" class="form-control" id="name" placeholder="Enter SubCategory Name">--}}
{{--                            </div>--}}
{{--                        </div>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--                <div class="modal-footer">--}}
{{--                    <button type="submit" class="btn btn-info waves-effect waves-light">Add</button>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </form>--}}


{{--    </div>--}}
{{--</div><!-- /.modal -->--}}

resources/views/admin/sub_category/edit.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category Create')
@section('admin_content')
    <div class="row">
        <div class="col-lg-6">
            <div class="card-box">
                <h4 class="header-title  text-center m-t-0 m-b-30"> Update Category</h4>
                <form method="post" action="{{ route('subcategory.update', $subcategory->id) }}">
                    @csrf
                    @method('PUT')
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <div class="form-group">
                            <label for="category_id">Category</label>
                            <input type="text" name="" class="form-control" id="category_id" value="{{ $subcategory->category->name}}" disabled>
                            <input type="hidden" name="category_id" class="form-control" id="category_id" value="{{ $subcategory->category->id}}">
                    </div>
                    <div class="form-group">
                        <label for="name">Sub Category Name</label>
                        <input type="text" name="name" class="form-control" id="name" value="{{ $subcategory->name }}">
                    </div>

                    <button type="submit" class="btn btn-info waves-effect waves-light">Update</button>
                </form>
            </div>
        </div><!-- end col -->
    </div>
@endsection

resources/views/admin/sub_category/index.blade.php
@extends('admin.admin_layouts')
@section('title', 'Category index')
@section('admin_content')

    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <h4 style="display: inline-block" class="header-title m-t-0 m-b-30">Sub Category Index</h4>
                <button   type="button" class="btn btn-info btn-rounded w-md waves-effect waves-light " data-toggle="modal" data-target="#category-create-modal"> Create New</button>


                <table id="datatable" class="table table-striped dt-responsive nowrap">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Category Name</th>
                        <th>Action</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach( $data['subcategories'] as $subcategory)
                        <tr>
                            <td>{{ $subcategory->id }}</td>
                            <td>{{ $subcategory->name }}</td>
                            <td>{{ $subcategory->category->name }}</td>

                            <td>
                                <a class="btn btn-primary btn-xs" href="{{ route('subcategory.edit', $subcategory->id) }} ">
                                    <i class="fa fa-edit">
                                    </i>
                                </a>

                                <a href="#" class="btn btn-danger btn-xs delete-modal" data-id="{{ $subcategory->id }}" data-toggle="modal" data-target=".sub_category_delete_modal">
                                    <i id="subCategoryName" data-id="{{ $subcategory->name }}" class="fa fa-trash">
                                    </i>
                                </a>
                            </td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div><!-- end col -->
    </div>
    <!-- end row -->

    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->


    <div id="category-create-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <form method="post" action="{{ route('subcategory.store') }}">
                @csrf
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                        <h4 class="modal-title"> Sub Category Add</h4>
                    </div>
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="name"> Category</label>
                                    <select class="form-control" name="category_id" required>
                                        <option value="">--Select a category--</option>
                                        @foreach($data['categories'] as $category)
                                            <option value="{{$category->id}}"> {{ $category->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                        </div><div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="name">Sub Category Name</label>
                                    <input type="text" name="name" class="form-control" id="name" placeholder="Enter SubCategory Name" required>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-info waves-effect waves-light">Add</button>
                    </div>
                </div>
            </form>


        </div>
    </div><!-- /.modal -->


    <!-- Delete Modal -->



    <div class="modal fade sub_category_delete_modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" style="display: none;">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                    <h4 class="modal-title" id="mySmallModalLabel">Are you sure?</h4>
                </div>
                <div class="modal-body">
                    <p id="sub_category_name">
                    {{--                    <form  action="{{route('category.delete', $category->id)}}" method="post">--}}
                    <form id="deleteForm" action="" method="post">
                        @csrf
                        @method('delete')
                        <button type="submit" class="btn btn-danger">
                            Delete
                        </button>
                    </form>
                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

@endsection

@section('on_page_js')
    <script>
        $(document).on("click", ".delete-modal", function () {
            let subCategoryId = $(this).data('id');
            let subCategoryName = $('#subCategoryName').data('id');
            $(".modal-body #sub_category_name").text( "Do you want to delete "+ subCategoryName +' Sub Category?' );
            var route = '/admin/subcategory/'+subCategoryId
            $('#deleteForm').attr('action', route)
        });

    </script>
@endsection